# Generated by Django 5.0.14 on 2026-04-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('capacite', models.PositiveIntegerField()),
                ('statut', models.CharField(choices=[('LIBRE', 'Libre'), ('OCCUPEE', 'Occupée'), ('RESERVEE', 'Réservée'), ('ENCAISSEMENT', 'Encaissement')], default='LIBRE', max_length=20)),
                ('pos_x', models.FloatField(default=0.0)),
                ('pos_y', models.FloatField(default=0.0)),
                ('est_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'ordering': ['numero'],
            },
        ),
    ]
