from decimal import Decimal


CURRENCY_QUANTUM = Decimal('0.01')
ZERO_AMOUNT = Decimal('0.00')

PAYMENT_METHOD_CARTE = 'CARTE'
PAYMENT_METHOD_ESPECES = 'ESPECES'
PAYMENT_METHOD_EN_LIGNE = 'EN_LIGNE'

PAYMENT_STATUS_EN_ATTENTE = 'EN_ATTENTE'
PAYMENT_STATUS_COMPLETE = 'COMPLETE'
PAYMENT_STATUS_ECHOUE = 'ECHOUE'
COMPLETED_PAYMENT_STATUSES = (PAYMENT_STATUS_COMPLETE,)

PAYABLE_COMMANDE_STATUSES = (
    'EN_COURS',
    'EN_CUISINE',
    'PRETE',
)

