# Generated by Django 5.0.14 on 2026-05-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_plat'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='plats', through='stock.PlatIngredient', to='stock.ingredient'),
        ),
    ]
