# Generated by Django 5.0.14 on 2026-05-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0002_paiement_client'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paiement',
            name='paiements_paiement_amount_gt_zero',
        ),
        migrations.RemoveIndex(
            model_name='paiement',
            name='paiements_p_command_12c36d_idx',
        ),
        migrations.RemoveIndex(
            model_name='paiement',
            name='paiements_p_referen_580f33_idx',
        ),
        migrations.AlterField(
            model_name='paiement',
            name='methode',
            field=models.CharField(choices=[('ESPECES', 'Espèces'), ('CARTE', 'Carte'), ('QR', 'QR Code')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('COMPLETE', 'Complété'), ('ECHOUE', 'Échoué')], default='EN_ATTENTE', max_length=20),
        ),
    ]
