# Generated by Django 5.0.14 on 2026-06-01 00:18

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0005_alter_commande_type'),
        ('paiements', '0003_remove_paiement_paiements_paiement_amount_gt_zero_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddConstraint(
            model_name='paiement',
            constraint=models.CheckConstraint(check=models.Q(('montant__gt', 0)), name='paiements_paiement_amount_gt_zero'),
        ),
    ]
