# Generated by Django 5.1.15 on 2026-06-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0004_alter_paiement_montant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('COMPLETE', 'Complété'), ('ECHOUE', 'Échoué')], db_index=True, default='EN_ATTENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
