# Generated by Django 5.0.14 on 2026-05-07 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('OUVERTURE', 'Ouverture'), ('FERMETURE', 'Fermeture'), ('HEBDOMADAIRE', 'Hebdomadaire')], max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Checklist',
                'verbose_name_plural': 'Checklists',
                'ordering': ['type', 'titre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Termine')], default='EN_COURS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='checklists.checklist')),
                ('execute_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Checklist execution',
                'verbose_name_plural': 'Checklist executions',
                'ordering': ['-date', 'checklist__type', 'checklist__titre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('est_obligatoire', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='checklists.checklist')),
            ],
            options={
                'verbose_name': 'Checklist task',
                'verbose_name_plural': 'Checklist tasks',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItemResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_complete', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_item_responses', to=settings.AUTH_USER_MODEL)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='checklists.checklistexecution')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='checklists.taskchecklist')),
            ],
            options={
                'verbose_name': 'Checklist item response',
                'verbose_name_plural': 'Checklist item responses',
                'ordering': ['task__ordre', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='checklistexecution',
            constraint=models.UniqueConstraint(fields=('checklist', 'date'), name='checklist_execution_unique_day'),
        ),
        migrations.AddConstraint(
            model_name='checklistitemresponse',
            constraint=models.UniqueConstraint(fields=('execution', 'task'), name='checklist_response_unique_task'),
        ),
    ]
