# Generated by Django 5.0.14 on 2026-05-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='cin',
            field=models.CharField(blank=True, default='', max_length=20, unique=True),
        ),
    ]
