# Generated by Django 5.0.14 on 2026-05-09 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_alter_employe_cin'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffreEmploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('SAISONNIER', 'Saisonnier')], default='CDI', max_length=20)),
                ('salaire_propose', models.CharField(blank=True, max_length=100)),
                ('est_publiee', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Offre d'emploi",
                'verbose_name_plural': "Offres d'emploi",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('message_motivation', models.TextField()),
                ('cv_url', models.URLField(blank=True, help_text='Lien vers le CV (ex: Google Drive, LinkedIn)')),
                ('statut', models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('ENTRETENUE', 'Entretien'), ('REFUSEE', 'Refusée'), ('RECRUTEE', 'Recrutée')], default='NOUVELLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='hr.offreemploi')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='hr.employe')),
            ],
            options={
                'ordering': ['jour', 'heure_debut'],
                'unique_together': {('employe', 'jour', 'heure_debut')},
            },
        ),
    ]
