# Generated by Django 5.0.14 on 2026-05-05 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('nombre_personnes', models.PositiveIntegerField()),
                ('statut', models.CharField(choices=[('CONFIRMEE', 'Confirmee'), ('ANNULEE', 'Annulee'), ('PRESENTE', 'Presente'), ('ABSENTE', 'Absente')], default='CONFIRMEE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='tables.table')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['date_reservation', 'heure_debut', 'id'],
                'indexes': [models.Index(fields=['table', 'date_reservation', 'heure_debut'], name='reserv_table_date_start_idx'), models.Index(fields=['table', 'date_reservation', 'statut'], name='reserv_table_date_status_idx'), models.Index(fields=['client', 'date_reservation'], name='reserv_client_date_idx')],
            },
        ),
    ]
