# Generated by Django 5.0.14 on 2026-05-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['date_reservation', 'heure_debut', 'id'], 'verbose_name': 'Réservation', 'verbose_name_plural': 'Réservations'},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('CONFIRMEE', 'Confirmée'), ('ANNULEE', 'Annulée'), ('PRESENTE', 'Présente'), ('ABSENTE', 'Absente')], default='CONFIRMEE', max_length=20),
        ),
    ]
