# Generated by Django 5.0.14 on 2026-05-05 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0002_plat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('unite_mesure', models.CharField(choices=[('g', 'Grammes'), ('ml', 'Millilitres'), ('pcs', 'Pièces')], max_length=5)),
                ('stock_actuel', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('seuil_alerte', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('est_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ingrédient',
                'verbose_name_plural': 'Ingrédients',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='PlatIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_requise', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_plats', to='stock.ingredient')),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plat_ingredients', to='menu.plat')),
            ],
            options={
                'verbose_name': 'Ingrédient du plat',
                'verbose_name_plural': 'Ingrédients des plats',
                'unique_together': {('plat', 'ingredient')},
            },
        ),
    ]
