# Generated by Django 5.0.14 on 2026-05-27 17:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_ingredient_seuil_alerte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée de stock'), ('SORTIE', 'Sortie de stock')], max_length=10)),
                ('source', models.CharField(choices=[('LIVRAISON', 'Livraison fournisseur'), ('ACHAT_PERSONNEL', 'Achat personnel'), ('AJUSTEMENT_INVENTAIRE', 'Ajustement inventaire'), ('CONSOMMATION_CUISINE', 'Consommation cuisine'), ('PERTE', 'Perte / Gaspillage')], max_length=30)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='stock.ingredient')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-created_at'],
            },
        ),
    ]
