# Generated by Django 5.0.14 on 2026-04-29 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0002_plat'),
        ('tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('EN_CUISINE', 'En cuisine'), ('PRETE', 'Prete'), ('PAYEE', 'Payee'), ('ANNULEE', 'Annulee')], default='EN_COURS', max_length=20)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('est_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serveur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='tables.table')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommandeLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_PREPARATION', 'En preparation'), ('PRET', 'Pret'), ('SERVI', 'Servi'), ('ANNULE', 'Annule')], default='EN_ATTENTE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commandes.commande')),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commande', to='menu.plat')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['statut', 'created_at'], name='commandes_c_statut_df764c_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['table'], name='commandes_c_table_i_54b3db_idx'),
        ),
        migrations.AddIndex(
            model_name='commandeligne',
            index=models.Index(fields=['commande', 'statut'], name='commandes_c_command_fddb51_idx'),
        ),
    ]
