# Generated by Django 5.0.14 on 2026-05-09 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_kds_orchestrator_fields'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='client_nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='type',
            field=models.CharField(choices=[('SUR_PLACE', 'Sur place'), ('EMPORTER', 'A emporter')], default='SUR_PLACE', max_length=20),
        ),
        migrations.AlterField(
            model_name='commande',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='tables.table'),
        ),
    ]
