# Generated by Django 5.0.14 on 2026-05-27 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_commande_client_nom_commande_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='commande',
            name='commandes_c_statut_df764c_idx',
        ),
        migrations.RemoveIndex(
            model_name='commande',
            name='commandes_c_table_i_54b3db_idx',
        ),
        migrations.AddField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mes_commandes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commande',
            name='serveur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_prises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('EN_CUISINE', 'En cuisine'), ('PRETE', 'Prête'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée')], default='EN_COURS', max_length=20),
        ),
        migrations.AlterField(
            model_name='commande',
            name='type',
            field=models.CharField(choices=[('SUR_PLACE', 'Sur place'), ('EMPORTER', 'À emporter')], default='SUR_PLACE', max_length=20),
        ),
        migrations.AlterField(
            model_name='commandeligne',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_PREPARATION', 'En préparation'), ('PRET', 'Prêt'), ('SERVI', 'Servi'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20),
        ),
    ]
