# Generated by Django 5.0.14 on 2026-05-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0004_remove_commande_commandes_c_statut_df764c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='type',
            field=models.CharField(choices=[('SUR_PLACE', 'Sur place')], default='SUR_PLACE', max_length=20),
        ),
    ]
