# Generated by Codex on 2026-06-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0005_alter_commande_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='type',
            field=models.CharField(choices=[('SUR_PLACE', 'Sur place'), ('EMPORTER', 'À emporter')], default='SUR_PLACE', max_length=20),
        ),
    ]
