# Generated by Django 5.1.15 on 2026-06-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0006_restore_emporter_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='est_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('EN_CUISINE', 'En cuisine'), ('PRETE', 'Prête'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée')], db_index=True, default='EN_COURS', max_length=20),
        ),
    ]
