# Generated by Django 5.0.14 on 2026-05-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantconfiguration',
            name='auto_send_main_course',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurantconfiguration',
            name='default_gratuity_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='restaurantconfiguration',
            name='gratuity_threshold',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='restaurantconfiguration',
            name='prep_target_minutes',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='restaurantconfiguration',
            name='primary_color',
            field=models.CharField(default='#FFB785', max_length=7),
        ),
        migrations.AddField(
            model_name='restaurantconfiguration',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
