# Generated by Django 5.0.14 on 2026-05-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='lang_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
