# Generated by Django 5.0.14 on 2026-05-27 21:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0003_analysesentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='note',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
