# Generated by Codex on 2026-06-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0004_alter_avis_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='avis',
            constraint=models.UniqueConstraint(
                condition=models.Q(commande__isnull=False, plat__isnull=False),
                fields=('user', 'commande', 'plat'),
                name='avis_unique_user_commande_plat',
            ),
        ),
    ]
