# Generated by Django 5.1.15 on 2026-06-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0005_sentiment_float_unique_paid_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysesentiment',
            name='date_analyse',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='analysesentiment',
            name='label',
            field=models.CharField(choices=[('POSITIF', 'Positif'), ('NEGATIF', 'Négatif'), ('NEUTRE', 'Neutre')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='avis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='avis',
            name='sentiment_score',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
